### ISSUE TITLE
Set up a CSR repository mirror

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-run-button#1]

**Comment by jamesward** [comment]
Why do we need to mirror?

**Comment by ahmetb** [comment]
Cloud Shell team needs it for audit purposes.
Also the base_image trigger has to use a CSR repo as the source (GCB limitation).

**Comment by jamesward** [comment]
Ah.  Cool.

**Comment by jamesward** [comment]
Is this one done?
