### ISSUE TITLE
Custom Service Name?

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#10]
Make it possible to customize the `SERVICE_NAME` possible via `app.json`

**Comment by jamesward** [comment]
See: https://github.com/jamesward/cloud-run-button/issues/4#issuecomment-491187004

**Comment by ahmetb** [comment]
Yeah I think we can allow reading it from app.json. 
It’s better than prompting for it.

**Comment by jamesward** [comment]
I think we can use the `name` field and sanitize/transform it normally:
https://devcenter.heroku.com/articles/app-json-schema#name

**Comment by ahmetb** [comment]
Yeah I suppose we can use the same sanitization as #9.

But app.json>name field seems very long for most Heroku apps. We'll probably end up joining  with `_`, and truncating (which isn't very nice)

**Comment by jamesward** [comment]
Could add an `id` field instead.  I think it's ok to extend the `app.json` with new stuff we need.

**Comment by ahmetb** [comment]
"id" sounds good.

**Comment by steren** [comment]
`name` would be more consistent with our how product refer to this, and Kubernetes

**Comment by Linda6533** [comment]
> Yeah I think we can allow reading it from app.json. 
> It’s better than prompting for it. 

Yes verify

**Comment by Linda6533** [comment]
Hope to write you more if chance !   do you ?Tell me your feeling about
