### ISSUE TITLE
Consider hosting the image at deploy.cloud.run/button.svg

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-run-button#101]
Today, the button is

`[![Run on Google Cloud](https://storage.googleapis.com/cloudrun/button.svg)](https://deploy.cloud.run)`

We could serve the .svg from deploy.cloud.run and change it to:

`[![Run on Google Cloud](https://deploy.cloud.run/button.svg)](https://deploy.cloud.run)`

This is mostly markup cosmetic, so not sure it's worth it.

**Comment by jamesward** [comment]
Think we should redirect to the existing CDN since serving it would regionalize it?  Which maybe doesn't matter since GitHub creates it's own CDN served version of referenced assets.

**Comment by jamesward** [comment]
BTW, I do like the clean cosmetics of this.

**Comment by ahmetb** [comment]
I am indifferent, but it helps us change the underlying url in case of an event like bucket changes.

**Comment by ahmetb** [comment]
Instead of serving, we’d probably just do a permanent redirect. 
And as James has said, these assets are mostly cached (maybe refreshed periodically, or upon file updates).
