### ISSUE TITLE
[Feature Request] Add configuration for Cloud Run CLI flags

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-run-button#108]
Setting flags such as max instance and memory size from the configuration json.

**Comment by ahmetb** [comment]
Related: was discussed a bit here https://github.com/GoogleCloudPlatform/cloud-run-button/pull/89#issuecomment-541079900

I think overall we need some property bag objects in app.json to control various aspects. Ideally, not a flat list, as that can result in gigantic objects over time as we add more flags to gcloud. So maybe some categorization of such objects can help.

**Comment by jamesward** [comment]
Mem & cpu options are now available via `app.json` See: #175

**Comment by benwinding** [comment]
Would also be great to have the `concurrency` flag too if possible!

**Comment by glasnt** [comment]
Many flags were added in #228; there needs to be some thought as to how to make these flags easier to add in the future; maybe directly passing through to gcloud run deploy?
