### ISSUE TITLE
[Feature Request] Works with private Github repos

### ISSUE THREAD

**Issue by averikitsch** [GoogleCloudPlatform/cloud-run-button#109]
Request to able to deploy a container from a private Github repo.

**Comment by ahmetb** [comment]
You mean you are able to, or you want it to?

This won't be easy, if possible for all. Open in Cloud Shell experience creates an incognito shell where there's no such credentials to get private Git repos.

So, Cloud Run Button is great for deploying off-the-shelf (i.e. public software) without knowing much about GCP, Cloud Run etc. However, for things that you’ve written for yourself, you should probably consider https://console.cloud.google.com/run UI or `gcloud run deploy`/`gcloud run services replace` command.

I'm eager to hear use cases. But if you're the person writing the code (i.e. private repo), there's no a lot this button can do for you and we have deployment experiences.

**Comment by averikitsch** [comment]
Ah I see thanks for the explanation. A data scientist really like the no fuss approach of the button, but works only in private repos.

**Comment by ahmetb** [comment]
Yeah I would redirect them to Cloud Run quickstarts/tutorials for self-serve.
