### ISSUE TITLE
Feature Request: Allow Verbose Mode

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#11]
Maybe when we first start running we display something like:
`Running in terse output mode - hit "v" to enter verbose mode`

In verbose mode we should show the `gcloud` commands we are running but not necessarily their output.

**Comment by ahmetb** [comment]
🤔 if it’s for our own debugging we may be able to use ctrl-d or something to catch the interrupt signal and allow verbose logging.

The library that prints spinner/progress won’t play nice with printing a line after itself while it’s spinning, also.

If it’s just the gcloud run deploy command you want to show, we show it at the end.

**Comment by jamesward** [comment]
Was thinking this was more for people who want to learn the commands.  We could in verbose mode disable the spinner.

**Comment by steren** [comment]
Even outside of verbose mode, I like the idea of teaching users about what's going on under the hood. Have you considered always show the run command? For example in a gray color.

The button is here for a wow effect, but one other goal should be to educate users about the "real"  way to deploy.

**Comment by ahmetb** [comment]
Yeah I'll take a look, maybe our spinner library allows deletion/reprinting of multi-line strings (via terminfo or something like that).

Otherwise I'll end up with something like:

```sh
INFO: Will run command:
    gcloud ... \
       ... \
       ...
[ / ] Deploying application bla bla
```
