### ISSUE TITLE
cloudshell_open won't: Incorrect Usage. flag provided but not defined: -page

### ISSUE THREAD

**Issue by ghchinoy** [GoogleCloudPlatform/cloud-run-button#114]
When launching the Cloud Run Button from a [readme](https://github.com/ghchinoy/eldamo-build/tree/cloudrunbutton), receiving the following error indicating an unknown flag, that stops the build/launch and disconnects the cloud shell.

```
Incorrect Usage. flag provided but not defined: -page
```

<img width="1204" alt="Screen Shot 2019-11-27 at 2 31 24 PM" src="https://user-images.githubusercontent.com/469685/69757771-756fa500-1123-11ea-8a01-22df69403ac9.png">

**Comment by jamesward** [comment]
Thanks for reporting!  It looks like a recent change to Cloud Shell is passing the new param.  I'm investigating that.

Also, I sent a PR with a few fixes:
https://github.com/ghchinoy/eldamo-build/pull/7

The git url was invalid so I just removed it since it isn't needed in this case.

**Comment by ghchinoy** [comment]
Thanks @jamesward !

**Comment by jamesward** [comment]
We are working on rolling out a new release with the fix now.

**Comment by jamesward** [comment]
BTW, I'll update this bug when the release is out.

**Comment by jamesward** [comment]
The fix for this is out.  Let us know if you have any other problems.  BTW, there is another open issue you may run into: #118
