### ISSUE TITLE
application url not displaying at the end of a successful build & deployment

### ISSUE THREAD

**Issue by ghchinoy** [GoogleCloudPlatform/cloud-run-button#118]
After a successful build and deploy, the cloud run container is deployed and running (verified via url obtained by gcloud & console), but is not displayed in cloud shell. 

The line [here](https://github.com/GoogleCloudPlatform/cloud-run-button/blob/master/cmd/cloudshell_open/main.go#L308) appears to output a blank `url` after "Your application is now live here:"

screenshots from two repos, attached.

<img width="581" alt="Screen Shot 2019-11-28 at 10 04 46 AM" src="https://user-images.githubusercontent.com/469685/69827298-5aad3700-11dc-11ea-9d13-7cd1c7a6d9e4.png">
<img width="563" alt="Screen Shot 2019-11-28 at 10 17 54 AM" src="https://user-images.githubusercontent.com/469685/69827299-5aad3700-11dc-11ea-8333-cb6dc68dc122.png">

**Comment by jamesward** [comment]
Thanks for reporting! Looks like a regression somewhere.  I'll investigate.

**Comment by ahmetb** [comment]
This is a gcloud CLI bug.

doesn't happen on 271.0.0 but happens on 272.0.0, opening an issue.

**Comment by ahmetb** [comment]
It seems like we've started using v1 api instead of v1beta1. 

So the new URL is at `status.address.url` instead of `status.domain` of Service object in the new API. We can't expect gcloud to be fixed here, so I sent #120.

**Comment by ghchinoy** [comment]
Thank you both for all the quick fixes!
