### ISSUE TITLE
Prompt for deployment region

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-run-button#12]
It's possible to list regions via the client library:

https://cloud.google.com/run/docs/reference/rest/v1alpha1/projects.locations/list

**Comment by jamesward** [comment]
This one will be hard from a UX standpoint because I don't think the user should have to answer a bunch of questions but it does seem like once Run supports more than `us-central1` this will be unavoidable.  Not sure how to balance that.
