### ISSUE TITLE
[Bug] Optional arguments aren't optional

### ISSUE THREAD

**Issue by andrewhowdencom** [GoogleCloudPlatform/cloud-run-button#128]
Hola crew, 

While deploying:

- https://github.com/ahmetb/serverless-registry-proxy

I encountered a problem in which the application attempted to parse the options but, as they are missing in `app.json` parsed a `nil` and SIGSEGV`'d. 

The following PR is designed to fixed it:

https://github.com/ahmetb/serverless-registry-proxy/pull/1

But I think the actual bug is in this application.

**Comment by jamesward** [comment]
Whoops! Hit by the billion dollar bug :)

I’ll get this fixed this afternoon.

**Comment by jamesward** [comment]
This bug was fixed by #127

But we do need to get a new version deployed.  I'll request that now.

**Comment by andrewhowdencom** [comment]
No worries! No rush from my side; I just patched the repo with the button I liked.

**Comment by jamesward** [comment]
This fix has been deployed.  Sorry that took so long!  Feel free to re-open if you are still having issues.  Thanks!
