### ISSUE TITLE
make hook scripts stdout/stderr outputs something else than green/red

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-run-button#130]
Colors in stderr/stdout are usually pretty misleading and we should use colors more sparingly. I think gray color would be better for hook command outputs.

![image](https://user-images.githubusercontent.com/159209/72293254-fae1e280-3607-11ea-8f8f-35734818b80e.png)

**Comment by jamesward** [comment]
`FgHiBlack` for both stderr & stdout?

**Comment by jamesward** [comment]
btw, psql is on the Cloud Shell image, which I'm sure you guessed.

**Comment by ahmetb** [comment]
gray seems better in my shell

![image](https://user-images.githubusercontent.com/159209/72298777-f1f70e00-3613-11ea-8d56-26ccb95edf43.png)
