### ISSUE TITLE
No Billing Error

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#138]
We have handling for helping the user setup billing, but unfortunately it doesn't work in all scenarios.  In a new account I'm getting:
```
demo@cloudshell:~$ cloudshell_open --repo_url "https://github.com/jamesward-demo/hello-php.git" --page "editor" --git_branch "master"
[ ✓ ] Cloned git repository https://github.com/jamesward-demo/hello-php.git.
[ ✓ ] Queried list of your GCP projects
[ ? ] Would you like to use existing GCP project  to deploy this app? Yes
Error: error determining if billing account is linked: exit status 1. output=
ERROR: (gcloud.beta.billing.projects.describe) could not parse resource []
```

**Comment by ahmetb** [comment]
Hmm that looks like a `gcloud` bug.

**Comment by ahmetb** [comment]
I also recall us trying with a new account and it was working fine.

We run `"gcloud", "beta", "billing", "projects", "describe", "-q", "--format=json", projectID` so I assume something gcloud does is failing.

**Comment by jamesward** [comment]
Oh, this failed because I didn't have any projects yet and our handling for that case is broken for some reason.  I'll investigate.
