### ISSUE TITLE
Unable to call an external Docker Registry

### ISSUE THREAD

**Issue by dduzgun-security** [GoogleCloudPlatform/cloud-run-button#147]
**Description**
While testing Cloud Run, we were unable to pull an image in another Container Registry source then gcr.io. Our goal is to pull an image from the GitHub Package : docker.pkg.github.com inside a GitHub Action to deploy in Cloud Run with GitOps flow.

`gcloud beta run deploy ${{ secrets.GCLOUD_APP_NAME }} --quiet --image docker.pkg.github.com/${{ github.repository }}/image --project ${{ secrets.GCLOUD_PROJECT }} --region us-central1 --platform managed`

**Error during the GitHub Action** 
`Expected [region.]gcr.io/repo-path[:tag or @digest], obtained docker.pkg.github.com/.../.../image`

@ahmetb - Will there be any changes regarding the Container Registry source for Cloud Run any soon?

Thank you,
Cheers.

**Comment by ahmetb** [comment]
This is not Cloud Run product feedback forum, so this should not be discussed here. 

Please search for Google Cloud Issue Tracker and report it there. 

For now Cloud Run only supports gcr.io registries.
