### ISSUE TITLE
Cloud Run API Activation Can Take Time

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#157]
![screenshot](https://user-images.githubusercontent.com/65043/78293142-57f18400-74e5-11ea-9ca3-9abf8e25fb50.png)

It is possible that our activation is not working correctly since that code changed recently.  So first we should test that.  If that is not the problem then we could poll after activation until it is actually activated.

**Comment by hostirosti** [comment]
Discovered by @hostirosti as seen in the screenshot. 
To give a bit more context, when the error appeared I went to the console and activated the API there, it was still not enabled. The 2nd attempt to publish went passed that step.

2 possible scenarios here:

1.  Enabling the API failed despite the green checkmark
2. The API got enabled but propagation takes some time -- thus we would have to wait and prob in the next step till it's shown enabled

**Comment by ahmetb** [comment]
Found the bug, sent a PR.
