### ISSUE TITLE
Hook Commands Don't Have All Envs

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#159]
I tried something that also needed `HOME`.  Should we enable all the host env vars to be passed to the hook commands?

**Comment by ahmetb** [comment]
yeah I think we should totally do that.
many env vars like LC_*, TERM, EDITOR ... can come in handy to hooks.

**Comment by ahmetb** [comment]
we need to remove this:


	pathEnv := fmt.Sprintf("PATH=%s", os.Getenv("PATH"))

and just construct the array like:

    hookEnvs := []string{a, b, c, os.Environ()...)
