### ISSUE TITLE
Memory Setting No Longer 512Mi

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#174]
We lost that default in the transition away from `gcloud`. I have a better fix in progress.

**Comment by ahmetb** [comment]
Ouch, I expected this would happen somewhere. Let me know if you need help.

**Comment by jamesward** [comment]
I actually need to see why some of my stuff exceeds that, cause it shouldn't.  But the PR is here:
https://github.com/GoogleCloudPlatform/cloud-run-button/pull/175
