### ISSUE TITLE
Support GitLab

### ISSUE THREAD

**Issue by tyayers** [GoogleCloudPlatform/cloud-run-button#176]
Wanted to use this with my GitLab project, but an error message is shown that only GitHub and Bitbucket are supported..  Why not support other git platforms like GitLab as well?  Thanks

**Comment by glasnt** [comment]
I took a look and it seems while GitLab is implemented from some perspectives, it doesn't work from others. 

Testing repo: https://gitlab.com/glasnt/hello-cloudrun

Clicking the button when the URL is just `https://deploy.cloud.run`, the follow plain HTML is returned:

"Cannot infer which repository to deploy (Referer header was not present).
Go back, and click the 'Run on Google Cloud' button directly from the repository page."

Specifying a ?git_repo=https://gitlab.com/glasnt/hello-cloudrun, a modal popup error from cloud shell: 
> Open in Cloud Shell
> Errors:
> The `git_repo` param is invalid or missing. `git_repo` must be a valid URL from either 'github.com' or 'bitbucket.org'.

From there, clicking 'Close', waiting for the shell to load, then entering: 
```
cloudshell_open --repo_url "https://gitlab.com/glasnt/hello-cloudrun.git" --page "shell"
```

Enters me into the expected workflow.

**Comment by jamesward** [comment]
Looks like there is a limitation with Cloud Shell that we will escalate internally.

**Comment by ahmetb** [comment]
Thanks @jamesward. Yeah, it seems like a check that was added after we started supporting GitLab. So the request doesn't even make it to our code currently.

**Comment by tyayers** [comment]
That would be great to get it working again.. Would love to use the button in Gitlab repos to easily push deployments to Cloud Run

**Comment by jamesward** [comment]
This appears to be fixed!
