### ISSUE TITLE
git_branch unsupported flag

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#18]
Set via the `cloudshell_git_branch` query param.

```
jlward4th@cloudshell:~$ cloudshell_open --repo_url "https://github.com/jamesward/hello-micronaut.git" --git_branch "dockerfile"
Incorrect Usage. flag provided but not defined: -git_branch

NAME:
   cloudshell_open - This tool is only meant to be invoked by Google Cloud Shell

USAGE:
   cloudshell_open [global options] command [command options] [arguments...]

VERSION:
   0.0.0

DESCRIPTION:
   Specialized cloudshell_open for the Cloud Run Button

COMMANDS:
     help, h  Shows a list of commands or help for one command

GLOBAL OPTIONS:
   --repo_url value
   --help, -h        show help
   --version, -v     print the version
Error: flag provided but not defined: -git_branch
```

**Comment by ahmetb** [comment]
I'm currently in favor of not adding extra flags unless it's requested by someone for a good reason. Most OSS projects use master branch by default, and they are supposed to deploy from HEAD anyway.

More importantly, a subdirectory flag (`-working_dir`) is probably going to be required.

**Comment by jamesward** [comment]
Deploying a non-master branch is something that gets used pretty often with Heroku Button and something I do for a variety of reasons (testing, reproducing issues, etc).  This isn't a blocker for initial release and might be a good one for me to try to work on.
