### ISSUE TITLE
Git Cloning get stuck if I try to implement it for Private repository

### ISSUE THREAD

**Issue by cloudbloqavi** [GoogleCloudPlatform/cloud-run-button#180]
It seems, Git Cloning get stuck if I try to implement it for Private repository.
Even it does not prompt for username/password.

Once I cancel the process and run "git clone" command again, the it prompts for username/password.

Is it a existing bug? Or is there any work around to fix this issue

**Comment by jamesward** [comment]
Right now we don't support private repos, see #94 #109 

Let us know if there is a new use case we should consider.
