### ISSUE TITLE
No Busy Spinner on Build

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#182]
I think the busy indicator used to spin during the build but it doesn't anymore.  Might be something I broke.

**Comment by ahmetb** [comment]
Found the issue. It's because we're calling actual build job before starting the spinner.
So it does show the spinner momentarily, but only after the build is completed. :)

![image](https://user-images.githubusercontent.com/159209/88221472-680aac00-cc19-11ea-8afd-ab5d3970f238.png)

**Comment by jamesward** [comment]
ah. I'm pretty sure i broke that :(
