### ISSUE TITLE
Inherited env not cascaded to hook command envs

### ISSUE THREAD

**Issue by tomlarkworthy** [GoogleCloudPlatform/cloud-run-button#183]
First time you run it, the system prompts for user input for extra env variables, and these are visible in command env.
The second time you run it, the system no longer prompts for user input, and the variables are missing from command env.
Changing the name of the var will get you back to 1.

**Comment by tomlarkworthy** [comment]
My mistake

**Comment by tomlarkworthy** [comment]
No I am pretty sure something is wrong with the step of extracting env variables from a previously deployed service

**Comment by jamesward** [comment]
Just to verify, this is on `prebuild` / `postbuild` right?

**Comment by tomlarkworthy** [comment]
Yeah I observed on postbuild. Looks like you found the issue
