### ISSUE TITLE
Cannot set container port

### ISSUE THREAD

**Issue by tomlarkworthy** [GoogleCloudPlatform/cloud-run-button#185]
Cloud Run supports setting the expected listening port (https://cloud.google.com/run/docs/reference/container-contract#port). This is option is not exposed here.

It is a helpful feature when you don't own the docker build step: e.g. https://hub.docker.com/r/crccheck/hello-world/

**Comment by ahmetb** [comment]
Agreed, yeah we'd need to expose a knob for this in app.json.
