### ISSUE TITLE
Docker Command Wrong

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#186]
When doing a docker build, the command listed is:
```
docker build --tag gcr.io/blah/asdf .
```
But since the project is in a subdir, that command doesn't work if the user copy & pastes it.  Maybe it'd work to just change the listed command to:
```
docker build --tag gcr.io/blah/asdf asdf
```

**Comment by ahmetb** [comment]
That’s a good point. Feel free to do a PR.
