### ISSUE TITLE
Project List More

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#19]
It wasn't clear in the UI that there were more project IDs beyond those listed.  After scrolling it is clear but I'd be nice to have a visual indicator as such.

**Comment by ahmetb** [comment]
This is gonna be hard to do.


Especially because the library we use doesn't have support for it. But the CLI prompt currently says `Use arrows to move`:

```
[ ? ] Choose a Google Cloud Platform project to deploy:  [Use arrows to move, space to select, type to filter]
❯ a
  b
  c
  d
  e
  f
  g
```

maybe we can increase the number of options shown to 2x?

**Comment by jamesward** [comment]
Or we could have the UI indicate how many projects are in the list to hint to the user that they might not be seeing all of them.

**Comment by ahmetb** [comment]
What do you recommend? Something like this?:

    [ i ] Found 153 projects in your account. 
    [ ? ] Choose a Google Cloud Platform project to deploy:  [Use arrows to move, space to select, type to filter]

**Comment by jamesward** [comment]
Yup!
