### ISSUE TITLE
Redirector With Explicit git_url From GitHub Loses Param

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#197]
I have a repo that hard codes the `git_repo` and `revision` params in the button:
https://github.com/jamesward/hello-java/tree/jdk15

But the redirector gets confused because it sees the referer as `https://github.com` and so it asks the user to still specify the repo.

**Comment by ahmetb** [comment]
I am OOO but can review a patch if you create. Should be as easy as fixing the if stmt.

**Comment by jamesward** [comment]
Thanks! Here is the PR: https://github.com/GoogleCloudPlatform/cloud-run-button/pull/199
