### ISSUE TITLE
Choose Google Account before launching Cloud Shell

### ISSUE THREAD

**Issue by hugelgupf** [GoogleCloudPlatform/cloud-run-button#200]
I'm logged into multiple Google accounts.

I clicked a Cloud Run button on a project. It launched cloud shell and all the stuff in my default account, without giving me the choice to switch to the right account before proceeding (and I couldn't even tell which account it was using).

I had to open an incognito window, log in to the desired google account only, and *then* click the deploy button there.

**Comment by ahmetb** [comment]
I suspect this issue should be opened to Cloud Console component on b/. 

Cloud Run Button runs as a program under Cloud Shell which is a UI experience under Cloud Console

There should be a profile picture on the top right of Cloud Console but I think you are right —"Open in Cloud Shell" shows a full-screen terminal emulator in the browser window. 

We can print the authenticated user email to the screen in the terminal, but not more than that here.

**Comment by hugelgupf** [comment]
Even with the profile picture, before I get there I am asked to "trust" the repo, and then allow it to use my credentials (which ones? hard to tell which account you're on). This happens with the background (and user switcher) greyed out. (Plus it didn't show me a profile picture, just a generic cutout?)

You're right, that's probably a Console issue.

**Comment by ahmetb** [comment]
Yeah it's a valid point, this applies to all "open in Cloud Shell" experiences. 

Filing a b/ to Cloud Shell component would be appropriate.

**Comment by hugelgupf** [comment]
Filed, thanks.
