### ISSUE TITLE
Add --use-http2 Option

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#202]
```
"options": {
  "use-http2": true
}
```

If `true` set `--use-http2`. If `false` then set `--no-use-http2`. If not set then omit.

**Comment by ahmetb** [comment]
more briefly `http2` might be better.

**Comment by jamesward** [comment]
So far we've tried to stay consistent with the CLI flags so like `allow-unauthenticated` == `--allow-unauthenticated` but I'm down with whatever.
