### ISSUE TITLE
Handling When Image Not Trusted

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#21]
Quick fix: Provide an error message and ask the user to try again and trust the image
Nicer fix: Have the user login, then continue

**Comment by ahmetb** [comment]
> Nicer fix: Have the user login, then continue

Sadly I'm not sure if this can be done without reloading the page (which doesn't have the initial URL with ?cloudshell_git_repo etc, so everything gets lost).
