### ISSUE TITLE
[Feature Request] Add configuration for Pack build

### ISSUE THREAD

**Issue by cage1016** [GoogleCloudPlatform/cloud-run-button#215]
[GoogleCloudPlatform/buildpacks: Builders and buildpacks designed to run on Google Cloud's container platforms](https://github.com/GoogleCloudPlatform/buildpacks#configuration)

https://github.com/GoogleCloudPlatform/cloud-run-button/blob/ff276c6f2ec7ff1b80710426bdc3d8eaafe3e2d6/cmd/cloudshell_open/pack.go#L23

hope to support pack env  configuration

**Comment by jamesward** [comment]
As discussed in #216 there is a way to do this with `package.toml` and we need to document that.  Sorry for the delay in responding!
