### ISSUE TITLE
cloud shell fails to enable required APIs

### ISSUE THREAD

**Issue by shamsmosowi** [GoogleCloudPlatform/cloud-run-button#223]
I've been using cloud-run-button for few months now, and it has been great for simplifying deployment!

past 2 days, I started getting this 500 Error after the `Enabling cloud run API ` step, it has been failing most of the time
```cloudshell_open --repo_url "https://github.com/GoogleCloudPlatform/cloud-run-hello.git" --page "shell" --force_new_clone
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
@cloudshell:~$ cloudshell_open --repo_url "https://github.com/GoogleCloudPlatform/cloud-run-hello.git" --page "shell" --force_new_clone
[ ✓ ] Cloned git repository https://github.com/GoogleCloudPlatform/cloud-run-hello.git.
[ ✓ ] Queried list of your projects
[ ? ] Would you like to use existing GCP project projectId to deploy this app? Yes
[ ✖ ] Failed to enable required APIs on project projectId.
Error: failed to list APIs on the project: googleapi: Error 500: An internal exception occurred.
Help Token: Ae-hA1N0clPv7i5vuFyRrZsjI2E6dy8bdUjEAGL8lMvvk5Tfyxwf2F3AOnxID9aTdeHdlc5SPe1tmkBOJnnRWuXuwdSllHpXBCv0APEraBamuAzB, backendError
@cloudshell:~$
```

Other users have reported the same issue, and I've created new projects and new google accounts, to see if its any misconfiguration on my side, But I can't seem to identify the cause of the Error.

**Comment by bofeiw** [comment]
I am seeing the same error.

```
Welcome to Cloud Shell! Type "help" to get started.
To set your Cloud Platform project in this session use “gcloud config set project [PROJECT_ID]”
cloudshell_open --repo_url "https://github.com/GoogleCloudPlatform/cloud-run-hello.git" --page "shell" --force_new_clone
bofeiw@cloudshell:~$ cloudshell_open --repo_url "https://github.com/GoogleCloudPlatform/cloud-run-hello.git" --page "shell" --force_new_clone
[ ✓ ] Cloned git repository https://github.com/GoogleCloudPlatform/cloud-run-hello.git.
[ ✓ ] Queried list of your projects
[ ✓ ] Found 8 projects in your GCP account.
[ ? ] Choose a project or press ctrl-c to create a new project: bobby-testing-webhooks
[ ✖ ] Failed to enable required APIs on project bobby-testing-webhooks.
Error: failed to list APIs on the project: googleapi: Error 500: An internal exception occurred.
Help Token: Ae-hA1OLU_kSHKxjecKl6fPZpb8P5JKsoyMxSUR5z1cR-QisnYDvGSmaLou1QBy1-yqQXGs3YhFAfPc88yk8lZwY_OzeQgZuzRFMdEtiOJ1DXNv7, backendError
bofeiw@cloudshell:~$
```

<img width="1140" alt="Screen Shot 2022-01-24 at 2 02 34 am" src="https://user-images.githubusercontent.com/34177142/150684770-af22431a-8fdf-4288-aff8-11bdb65c0f4d.png">

**Comment by jamesward** [comment]
I'm investigating this.

**Comment by jamesward** [comment]
I'm working on getting this fix deployed.

**Comment by shamsmosowi** [comment]
thanks @jamesward !, is it deployed yet? or is there any ETA for it?

**Comment by jamesward** [comment]
It is rolling out now and should be 100% in the next 48ish hours.  BTW, if you are looking for automated releases check out a better way: https://www.youtube.com/watch?v=vwh4hLGDxFw

**Comment by shamsmosowi** [comment]
We're actually use it for [user onboarding](https://github.com/rowyio/rowyrun), mainly using it like @tomlarkworthy [minecraft server](https://github.com/boardingparty/minecraft_gcp) for terraform deployment.
Thanks again for getting the issue resolved promptly!

**Comment by jamesward** [comment]
Ah cool.  Thanks!

**Comment by jamesward** [comment]
It appears this fix has been rolled out and everything seems to be good now.  Let me know if you have any issues.
