### ISSUE TITLE
deploy.cloud.run redirect doesn't load cloudshell image

### ISSUE THREAD

**Issue by shamsmosowi** [GoogleCloudPlatform/cloud-run-button#225]
the deploy.cloud.run [redirect](https://deploy.cloud.run/?git_repo=https://github.com/GoogleCloudPlatform/cloud-run-hello.git) is not opening cloudshell with the button image anymore, instead just opening a blank terminal.

The direct cloud shell [link](https://ssh.cloud.google.com/cloudshell/editor?cloudshell_git_repo=https://github.com/GoogleCloudPlatform/cloud-run-button.git&cloudshell_image=gcr.io/cloudrun/button&shellonly=true) is able to run the image

**Comment by jamesward** [comment]
This appears to have been resolved.  Maybe a fix in Cloud Shell.  Can you verify it is working for you now?

**Comment by shamsmosowi** [comment]
yes, it's working now 👍
