### ISSUE TITLE
Cloud Run Button clicks now redirect to Cloud Shell Editor

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/cloud-run-button#226]
I tried using a Cloud Run Button earlier today, and instead of getting the Cloud Shell opening my repo and asking me where I want to deploy, I end up in a view that is both the Cloud Shell Editor and Terminal, but no `cloudshell_open` command is run.

**Comment by jamesward** [comment]
Eek. Sure enough. Looks like a Cloud Shell bug. I'll escalate.

**Comment by glasnt** [comment]
This was resolved shortly after the report.
