### ISSUE TITLE
Tell me how to remove it, or what happens if I don't

### ISSUE THREAD

**Issue by craigbox** [GoogleCloudPlatform/cloud-run-button#38]
The script output tells me how to change the image and deploy a new version, but it doesn't tell me how to remove it.

It also doesn't tell me what happens if I don't - will it live forever? Will it expire?  Will I have to pay anything

**Comment by ahmetb** [comment]
Good point. Something like this could solve the problem:

```
Your application is billed only when it receives requests.
To manage this application, go to https://console.cloud.google.com/run
```

**Comment by craigbox** [comment]
Don't forget `?project=_____` because it opened in a different project than I had deployed when I copied/pasted that link.

**Comment by ahmetb** [comment]
Yeah, thanks for the reminder.
