### ISSUE TITLE
Document the use of `cloudshell_working_dir`

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/cloud-run-button#40]
The support for working dir from https://github.com/GoogleCloudPlatform/cloud-run-button/pull/26 needs documentation.

**Comment by grayside** [comment]
If the directory does not exist, this error comes up:
```
Error: sub-directory doesn't exist in the cloned repository: [your configured subdir]
```

I ran into this because the default branch did not have my sub-directory, so I was able to delete the cloned repository and re-run the displayed cloud_shell command with the --git_branch flag.

**Comment by ahmetb** [comment]
I think it's expected?

**Comment by grayside** [comment]
This is a troubleshooting note for the future documentation.
