### ISSUE TITLE
cloning repo means you can only ever use the button once

### ISSUE THREAD

**Issue by poy** [GoogleCloudPlatform/cloud-run-button#45]
The way the button clones the repo implies that you can only ever use the button once. After the first use, it will fail.

**Comment by poy** [comment]
This could be due to something related to CS.

**Comment by jamesward** [comment]
It looks like when using a custom image the home dir is fresh each time.  At least it should be.  When using the default image the home dir is persistent.  I tried two deploys in quick succession and didn't have a git checkout issue.

**Comment by ahmetb** [comment]
That's been my experience as well. But it might be very well a Cloud Shell bug that occurs under certain circumstances and timing. If you can reliably repro, we should report it.
