### ISSUE TITLE
Update gcloud command to use --platform managed

### ISSUE THREAD

**Issue by steren** [GoogleCloudPlatform/cloud-run-button#47]
Very soon, `--platform managed` will be required when running `gcloud beta run deploy` to deploy to the managed version of Cloud Run without prompt.

**Comment by jamesward** [comment]
That vs Cloud Run on GKE?  Is it optional now? (i.e. can we safely add it now?)

**Comment by steren** [comment]
It's optional in the latest version of gcloud, and will become required soon

**Comment by ahmetb** [comment]
we currently have a `-q` in deploy command (disables prompts, accepts default).
once cloudshell base image ships with a version that offers --platform, we can update.

**Comment by steren** [comment]
As mentioned in previous comment, gcloud accepts `--platform` today
