### ISSUE TITLE
More Lenient app.json Parsing

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#53]
Trying the button on:
https://github.com/bkimminich/juice-shop.git

I get:
```
james_demo@cloudshell:~$ cloudshell_open --repo_url "https://github.com/bkimminich/juice-shop.git"
[ ✓ ] Cloned git repository https://github.com/bkimminich/juice-shop.git.
Error: error attempting to read the app.json from the cloned repository: failed to parse app.json file: failed to parse app.json: json: unknown field "description"
```

Reproduce with:
https://console.cloud.google.com/cloudshell/editor?shellonly=true&cloudshell_image=gcr.io/cloudrun/button&cloudshell_git_repo=https://github.com/bkimminich/juice-shop.git

**Comment by ahmetb** [comment]
What would be the motivation behind this?
Suppose there's an important field there we don't support, like "secret" or
"buildpack". What’s the point of proceeding?

**Comment by jamesward** [comment]
We will only ever support a subset of what Heroku makes possible in `app.json` so it makes sense to continue no matter what is there.  We could add warnings when things are encountered which are not supported.  Not supporting something specified in `app.json` doesn't mean we shouldn't / can't proceed.

**Comment by ahmetb** [comment]
> Not supporting something specified in `app.json` doesn't mean we shouldn't / can't proceed.

I feel like this won't generally hold true. There are critical fields like `stack`, `buildpacks` that has to be taken into account. Ignoring those sound wrong.

We can add "silent" unused fields to unblock harmless fields (like `description`, `logo`, `website`) but I'm currently -1 for silently ignoring fields. (Also Go's JSON parser doesn't make it easy to get a "list of unrecognized fields").

**Comment by jamesward** [comment]
Yeah, makes sense.  We can defer specifics until we encounter them.  Like when someone tries our button with a repo that includes `stack` we can evaluate if we can ignore or if we need to handle.  For now, this is the `app.json` I ran into errors with:
https://github.com/bkimminich/juice-shop/blob/master/app.json

Seems like there isn't anything in there we can't support or ignore safely.

**Comment by ahmetb** [comment]
So instead of disabling validation altogether I recommend you come up with a list of repos with app.json that you think should work with the button today, and we silently parse+ignore those.

**Comment by jamesward** [comment]
Looking through just mine:
https://github.com/search?l=&p=1&q=user%3Ajamesward+filename%3Aapp.json&type=Code

Of the ones that will work here are the common fields:
```
{
  "name": "String",
  "description": "String",
  "repository": "URL",
  "logo": "URL",
  "website": "URL",
  "keywords": ["String", "String"],
  "env": {
    "String": {
      "description": "String",
      "generator": "secret",
      "value": "String",
      "required": Boolean
    }
  }
}
```

**Comment by ahmetb** [comment]
So we're good if we silently enable .logo, .keywords, .website, .description?

I'm hesitant about the non-docs fields that are actually supposed to do something.

**Comment by jamesward** [comment]
Yup!  Let's start there and deal with other cases as they arise.

**Comment by jamesward** [comment]
This change has been deployed and seems to be working as expected.
