### ISSUE TITLE
malformed output

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-run-button#61]
![image](https://user-images.githubusercontent.com/159209/61676006-37fb9680-acaf-11e9-9dcb-309e7c146672.png)

looks like this wasn't tested properly :)

**Comment by jamesward** [comment]
I think there was some weird condition where this didn't always happen.  I didn't see it in my recent testing.

**Comment by ahmetb** [comment]
Probably when the image builds immediately without the spinner spinning more than one frame.
