### ISSUE TITLE
Is it possible to deploy a container directly ?

### ISSUE THREAD

**Issue by atakanyenel** [GoogleCloudPlatform/cloud-run-button#67]
If I have a public image in gcr.io, can I give the button required parameters and when clicked, it opens the window for cloud run and the image name is already filled out ?

I don't want user to build the repo or so, just autofill the image name in Cloud run and if possible add some env variables ?

**Comment by ahmetb** [comment]
Not currently. We only deploy from source.

**Comment by jamesward** [comment]
It would be nice if there were a URL query param for the container image at: https://console.cloud.google.com/run/create

cc @steren

**Comment by steren** [comment]
There is, you can pass the image and name as URL parameters. This is used in Google Container Registry UI to provide a Deploy button

**Comment by ahmetb** [comment]
That's good to know, thanks Steren. It appears like this is just a documentation issue.

We can tell people to modify the button’s link to point to the console.cloud.google.com URL with the pre-built image. I don't think we should try to address that in the code.

**Comment by jamesward** [comment]
Yeah, no code change needed.

Here is the URL:
```
https://console.cloud.google.com/run/create?image=IMAGE
```

So like:
```
https://console.cloud.google.com/run/create?image=gcr.io/cloudrun/hello
```

Anyone can use the Deploy Button Image with that URL.

**Comment by steren** [comment]
This link does not behave well if users do not have a GCP project and if they have not enabled Cloud Run. This is why is it nowhere in our documentation. It is not *yet* an official product surface.

**Comment by jamesward** [comment]
Yeah, that makes sense.  So some button-like project could smooth that experience.  But maybe not something that makes sense to put into this project.

**Comment by ahmetb** [comment]
Closing for now, maybe we can reconsider later.
