### ISSUE TITLE
Repo calling v1beta1 that doesn't exist

### ISSUE THREAD

**Issue by siamsot** [GoogleCloudPlatform/cloud-run-button#68]
v1beta1 is called (for example here: https://github.com/GoogleCloudPlatform/cloud-run-button/blob/master/cmd/cloudshell_open/cloudrun.go) However, it doesn't exist as a 404 error is returned. Also, it's not mentioned in the public documentation (https://cloud.google.com/run/docs/reference/rest/) nor the Google API repos (https://github.com/googleapis/google-api-go-client/tree/master/cloudbuild)

**Comment by ahmetb** [comment]
Thanks for reporting the issue is valid. Working on a fix.

**Comment by ahmetb** [comment]
Manually verified the fix is working.
