### ISSUE TITLE
Have the button demo work with cloudrun/hello image

### ISSUE THREAD

**Issue by ahmetb** [GoogleCloudPlatform/cloud-run-button#7]
@steren can we have the cloudrun/hello image open sourced (I'm thinking on its own repo) so that we can have the demo work with a repo that actually has code in it?

**Comment by jamesward** [comment]
I think we should put it in this repo so everything is in one place.  Then we can setup a way to serve it via CDN, or maybe GitHub sets up a CDN for us for static assets served from READMEs.

**Comment by steren** [comment]
Yes, I want to open source gcr.io/cloudrun/hello (internal issue is 129297571, feel free to pick it).

However, the demo is 100% independent from the button, so the code should live in another repo.

**Comment by ahmetb** [comment]
Yeah, my intention is to add the button to that repo, and use that app primarily to demo the button.

**Comment by jamesward** [comment]
Oh wow.  When I read this I for some reason was thinking of the PNG button image not the container image.  Sorry for my totally confusing comment.

**Comment by jamesward** [comment]
Is this https://github.com/GoogleCloudPlatform/cloud-run-hello or is that something else?

**Comment by steren** [comment]
Yep that's the one. I think we can close.
