### ISSUE TITLE
Build Script to Enable Jib and Other Builds

### ISSUE THREAD

**Issue by jamesward** [GoogleCloudPlatform/cloud-run-button#85]
It'd be nice if we could enable a way to run Jib builds via Maven or Gradle.  The `app.json` could include something like:
```
{
    "scripts": {
        "build": "./mvnw compile jib:build -Dimage=gcr.io/${PROJECT_ID}/hello-springboot"
    }
}
```
If that is set, we run the command instead of `docker build` or buildpack stuff.  We'd have to set the `PROJECT_ID` env var when we run the build command.

Note that this example requires a JVM which Cloud Shell has, but if the user needs other system deps they could add a build shell script to install them, and then specify that script.

**Comment by ahmetb** [comment]
What if we brought the cloudbuild support back? That would eliminate the need for this.

Otherwise a more extensible design would be preferable that allows us plugging in cmd, docker, cloudbuild.

**Comment by jamesward** [comment]
Yeah, I like that better than adding yet another way to run the build.  For reference, the feature request for Cloud Build support is: https://github.com/GoogleCloudPlatform/cloud-run-button/issues/14

**Comment by ahmetb** [comment]
Honestly I feel like this request is valid, because I can see people would do non-trivial multi-step builds.

That's where arbitrary commands like Jib or ko can help, but granted, we need to bring them to the build environment by pre-installing.

**Comment by jamesward** [comment]
Are you saying we should do something like above in addition to Cloud Build support?

**Comment by jamesward** [comment]
I'm thinking about adding this since we've already figured out how to add / run scripts.  So we could allow a custom build via:
```
    "hooks": {
        "build": {
            "commands": [
                "./foo.sh"
            ]
        }
    }
```

This would take precedence over `Dockerfile`, Maven Jib, and Buildpacks.  Adding a 4th way to build isn't ideal, but I continue to run across places where my build produces the container image and there isn't another good way to handle this (except maybe Cloud Build support).
