### ISSUE TITLE
Use pack CLI in Cloud Shell

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/cloud-run-button#93]
Cloud Shell will soon ship the most recent `pack` CLI (v0.4.1) for Buildpacks. There have been many changes to the Buildpacks spec; hopefully nothing breaks.

Also, the binary will be placed under `/usr/local/bin/pack` where the current `Dockerfile` tries to create a symlink. The symlink command will probably break by then.

**Comment by jamesward** [comment]
See #87

**Comment by jamesward** [comment]
What is the thing about the symlink? Can you provide more details?

**Comment by chanseokoh** [comment]
This line: https://github.com/GoogleCloudPlatform/cloud-run-button/blob/e2c4fa243a2c76142f654ca2eec6a31f84fe3610/Dockerfile#L19

When `/usr/local/bin/pack` is provided in the Cloud Shell base image, I think the command will fail. Basically what I am saying is if `pack` becomes available, we should update the `Dockerfile`.

**Comment by jamesward** [comment]
Oh, have you heard that they are talking about adding pack to the base image?

**Comment by chanseokoh** [comment]
Yeah, see the internal bug 141612258. They just need to rebuild and roll out the new Cloud Shell image.

**Comment by jamesward** [comment]
Oh! Thanks for the heads up.  At that point we can just drop our inclusion of pack from here.

**Comment by ahmetb** [comment]
Especially helpful since we have no build failure alerting from GCB.

**Comment by chanseokoh** [comment]
It went live. `/usr/local/bin/pack` is now included in Cloud Shell by default.
